### ISSUE TITLE
Instructions for MacOSX

### ISSUE THREAD

**Issue by ocervell** [GoogleCloudPlatform/cloud-debug-python#7]
Importing the library failed on MacOSX (installation succeeded after installing XCode).

This is the stacktrace:

```
>>> import googleclouddebugger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/googleclouddebugger/__init__.py", line 30, in <module>
    from . import breakpoints_manager
  File "/Library/Python/2.7/site-packages/googleclouddebugger/breakpoints_manager.py", line 22, in <module>
    from . import python_breakpoint
  File "/Library/Python/2.7/site-packages/googleclouddebugger/python_breakpoint.py", line 22, in <module>
    from . import capture_collector
  File "/Library/Python/2.7/site-packages/googleclouddebugger/capture_collector.py", line 33, in <module>
    from . import cdbg_native as native
ImportError: dlopen(/Library/Python/2.7/site-packages/googleclouddebugger/cdbg_native.so, 2): no suitable image found.  Did find:
	/Library/Python/2.7/site-packages/googleclouddebugger/cdbg_native.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Library/Python/2.7/site-packages/googleclouddebugger/cdbg_native.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

**Comment by hrasadi** [comment]
I am closing this due to inactivity and lack of context. Feel free to reopen if needed.
